name: yarn CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      
    - name: Check CNAME Contents
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./static/CNAME

    - name: CNAME Contents
      run: echo "${ steps.package.outputs.content }"

    - name: Build Setup
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Get Dependencies
      run: yarn

    - name: Build
      run: yarn build